### ISSUE TITLE
Alta Via 1 availability

### ISSUE THREAD

**Issue by leonlan** [leonlan/avplanner#1]
Could be interesting to work on an AV Planner website too. But there is a small problem that these don't have a centralized website, so it's a lot of custom scraping.

https://bookatrekking.com/nl/blog/alta-via-1/

- [x] https://www.pederue.it/en#Y7D0a11V
- [x] https://rifugiolagazuoi.com/EN/disponibilita.php?prm=8&chm=1#TabDisp
- [x] https://rifugioaverau.bukly.com/
- [x] https://www.staulanza.it/Booking/EN/prenotazione1.php
- [x] https://rifugiovazzoler.com/Booking/index_en.php
- [ ] Rifugio Carestiato 
- [ ] Rifugio Pian de Fontana

https://www.moonhoneytravel.com/europe/italy/dolomites/alta-via-1-hike/

- [ ] Stage 1 | Lago di Braies – Rifugio Biella (or Rifugio Sennes)
    - [x] Biella: https://www.planyo.com/booking.php?calendar=67368&mode=resource_list&planyo_lang=EN&feedback_url=https%3A%2F%2Fwww.planyo.com%2Fbooking.php%3Fcalendar%3D67368
    - [ ] Senne
- [ ] Stage 2 | Rifugio Biella – Rifugio Fanes (or Rifugio Lavarella)
    - [x] Fanes: https://www.rifugiofanes.com/en/booking.htm
    - [x] Lavarella: https://lavarella.it/en/book-online
- [ ] Stage 3  |Rifugio Fanes – Rifugio Lagazuoi
    - [x] Lagazuoi (above)
- [ ] Stage 4 | Rifugio Lagazuoi – Rifugio Nuvolau (or Rifugio Averau)
    - [x] Nuvolau: https://rifugionuvolau.it/language/en/sleeping/
    - [x] Averau (above)
- [ ] Stage 5 | Rifugio Nuvolau – Rifugio Città di Fiume
    - [x] https://rifugiocittadifiume.it/prenota/
- [ ] Stage 6 | Città di Fiume – Rifugio A. Sonino Al Coldai
    - [x] https://rifugiocoldai.com/Booking/index_en.php
- [ ] Stage 7 | Rifugio A. Sonino Al Coldai – Rifugio Vazzoler
    - [x] See above
- [ ] Stage 8 | Rifugio Vazzoler – Rifugio Carestiato (or Passo Duran)
    - [ ] Carestiato: Not available
    - [x] Passo Duran: https://rifugiopassoduran.it/prenotazione/
- [ ] Stage 9 | Rifugio Carestiato – Rifugio Pramperet (or Rifugio Pian de Fontana)
    - [ ] Pramperet None
    - [ ] Fontana None
- [ ] Stage 10 | Rifugio Pramperet – La Pissa Bus Stop  – Bus to Belluno

**Comment by leonlan** [comment]
[google.com/maps/d/u/0/viewer?mid=1isVS42rkRtx9E_F5SbDqNltgmtIpEjaQ&femb=1&ll=46.49674743900033,12.203265086175739&z=11](https://www.google.com/maps/d/u/0/viewer?mid=1isVS42rkRtx9E_F5SbDqNltgmtIpEjaQ&femb=1&ll=46.49674743900033%2C12.203265086175739&z=11)

GPT4o results

<details>
<summary>Query</summary>
```
### list all rifugios
Stage 1: Lago di Braies - Rif. Biella
Alta Via 1 - Stage 1
Rifugio Biella
Tourenplanung am 2023-03-12
Croda del Becco / Seekofel
Stage 2: Rif. Biella - Rif. Fanes
Alta Via 1 - Stage 2
Rifugio Fanes - Fanes Hütte
Alpine Guesthouse / Berggasthaus Pederü in S. Vigilio
Rifugio Sennes - Sennes Hütte
Rifugio Fodara Vedla
Rifugio Lavarella - Schutzhütte Lavarella
Stage 3: Rif. Fanes - Rif. Lagazuòi
Alta Via 1 - Stage 3
Capanna Alpina Hut / Hütte
Rifugio Lagazuòi 
Rifugio Scotoni - Scotoni Hütte
Stage 4: Rif. Lagazuoi - Rif. Nuvolau
Lago di Limides
Galleria Lagazuoi
Rifugio Nuvolau
Rifugio Averau
Alta Via 1 - Stage 4
Alta Via 1 - Stage 4
Rifugio 5 Torri
Rifugio Angelo Dibona
Passo Falzarego
Stage 5: Rif. Nuvolau - Rif. Citta di Fiume
Rifugio Città di Fiume
Passo Giao
Forcella Ambrizzola
Alta Via 1 - Stage 5
Laghetto di Baste
Rifugio Croda da Lago / Palmieri
Exit Route via Lago Federa
Stage 6: Rif. Citta di Fiume - Rif. Al Coldai
Rifugio Al Coldai a. Sonino 
Alta Via 1 - Stage 6
Stage 7: Rif. Coldai - Rif. Vazzoler - Rif. Trieste
Lake Coldai
Rifugio Attilio Tissi 
Alta Via 1 - Stage 7
Rifugio Capanna Trieste
Rifugio Mario Vazzoler 
Alta Via 1 - Stages 8 -10
Bus Stop Sr203 La Pissa
Rifugio C. Tomé @ Passo Duran
Rifugio Pian de Fontana 
Alta Via 1 - Stage 7-10
Rifugio Sommariva Al Pramperet 
Rifugio Bruto Carestiato
Bus Stop Listolade
Exit Route to Listolade Bus Stop 
```



</details>

**Stage 1: Lago di Braies - Rifugio Biella**
1. Rifugio Biella

**Stage 2: Rifugio Biella - Rifugio Fanes**
2. Rifugio Fanes
3. Alpine Guesthouse / Pederü
4. Rifugio Sennes
5. Rifugio Fodara Vedla
6. Rifugio Lavarella

**Stage 3: Rifugio Fanes - Rifugio Lagazuòi**
7. Capanna Alpina Hut
8. Rifugio Lagazuòi
9. Rifugio Scotoni

**Stage 4: Rifugio Lagazuòi - Rifugio Nuvolau**
10. Rifugio Nuvolau
11. Rifugio Averau
12. Rifugio 5 Torri
13. Rifugio Angelo Dibona

**Stage 5: Rifugio Nuvolau - Rifugio Città di Fiume**
14. Rifugio Città di Fiume
15. Rifugio Croda da Lago / Palmieri

**Stage 6: Rifugio Città di Fiume - Rifugio Al Coldai**
16. Rifugio Al Coldai (Sonino)

**Stage 7: Rifugio Coldai - Rifugio Vazzoler - Rifugio Trieste**
17. Rifugio Attilio Tissi
18. Rifugio Mario Vazzoler
19. Rifugio Capanna Trieste

**Stages 8-10**
20. Rifugio C. Tomé (Passo Duran)
21. Rifugio Pian de Fontana
22. Rifugio Sommariva Al Pramperet
23. Rifugio Bruto Carestiato

**Comment by leonlan** [comment]
### Organized Hut Information with Booking Details by Stages

#### **Stage 1: Lago di Braies - Rifugio Biella**
1. **Rifugio Biella**
   - **Booking**: [Planyo Booking](https://www.planyo.com/booking.php?calendar=67368&mode=resource_list&planyo_lang=EN&feedback_url=https%3A%2F%2Fwww.planyo.com%2Fbooking.php%3Fcalendar%3D67368)
     - Separate calendars for each bed type; availability described as 'av'.
    - [ ] Page of bed types
    - [ ] For each bed type we have a separate calendar
    - [ ] Restful api call to https://www.planyo.com/booking.php?calendar=67368&feedback_url=https%3A%2F%2Fwww.planyo.com%2Fbooking.php%3Fcalendar%3D67368&mode=reserve&planyo_lang=en&prefill=true&resource_id=224732& and then each day has 'av' availability description

#### **Stage 2: Rifugio Biella - Rifugio Fanes**
2. **Rifugio Fanes**
   - **Booking**: [Rifugio Fanes Booking](https://www.rifugiofanes.com/en/booking.htm)
     - Availability calendar with daily availability per bed type.
3. **Alpine Guesthouse / Pederü**
   - **Booking**: [Pederü Booking](https://www.pederue.it/en#Y7D0a11V)
     - 5 types of beds (Dorms, Single, Double, Triple, Quadruple); availability checked per bed type.
     - It's not possible to see how many beds are available. But you can click on a bed type and then see the availability calendar. This is a minor inconvenience because we cannot show the full information to users.

4. **Rifugio Sennes**
5. **Rifugio Fodara Vedla**
6. **Rifugio Lavarella**
   - **Booking**: [Rifugio Lavarella Booking](https://lavarella.it/en/book-online)
     - Follows a similar process to check availability with a straightforward interface.

#### **Stage 3: Rifugio Fanes - Rifugio Lagazuòi**
7. **Capanna Alpina Hut**
8. **Rifugio Lagazuòi**
   - **Booking**: [Rifugio Lagazuòi Availability](https://rifugiolagazuoi.com/EN/disponibilita.php?prm=8&chm=1#TabDisp)
     - Availability calendar per month; a daily modal shows the number of available beds.
9. **Rifugio Scotoni**

#### **Stage 4: Rifugio Lagazuòi - Rifugio Nuvolau**
10. **Rifugio Nuvolau**
    - **Booking**: [Rifugio Nuvolau Booking](https://rifugionuvolau.it/language/en/sleeping/)
 	- [ ] This is very simple. It shows an availability calendar for a month. Clicking on a cell shows a modal with the number of beds available. The divs with id "giorno<day>" show the number of beds available.

11. **Rifugio Averau**
    - **Booking**: [Rifugio Averau Booking](https://rifugioaverau.bukly.com/)
    	- 15-day calendar indicating yes/no availability per bed type; detailed daily availability.
		- [ ] 15 day calendar with for each bed type the yes/no availability of a given date.
		- [ ] Upon closer inspection on the day itself, you get more information + number of availability. Scraping can be done in a two-tier fashion
12. **Rifugio 5 Torri**
13. **Rifugio Angelo Dibona**

#### **Stage 5: Rifugio Nuvolau - Rifugio Città di Fiume**
14. **Rifugio Città di Fiume**
    - **Booking**: [Rifugio Città di Fiume Booking](https://rifugiocittadifiume.it/prenota/)
      - Simple booking system indicating the availability of beds.
15. **Rifugio Croda da Lago / Palmieri**

#### **Stage 6: Rifugio Città di Fiume - Rifugio Al Coldai**
16. **Rifugio Al Coldai (Sonino)**
    - **Booking**: [Rifugio Al Coldai Booking](https://rifugiocoldai.com/Booking/index_en.php)
      - Similar booking system with high-level availability and a zoomed-in lower-level view.

#### **Stage 7: Rifugio Coldai - Rifugio Vazzoler - Rifugio Trieste**
17. **Rifugio Attilio Tissi**
18. **Rifugio Mario Vazzoler**
    - **Booking**: [Rifugio Vazzoler Booking](https://rifugiovazzoler.com/Booking/index_en.php)
      - Similar booking system with high-level availability and bed details.
19. **Rifugio Capanna Trieste**

#### **Stages 8-10**
20. **Rifugio C. Tomé (Passo Duran)**
    - **Booking**: [Rifugio Passo Duran Booking](https://rifugiopassoduran.it/prenotazione/)
      - Two-tier system for high-level and detailed availability checking.
21. **Rifugio Pian de Fontana** (No booking link available)
22. **Rifugio Sommariva Al Pramperet** (No booking link available)
23. **Rifugio Bruto Carestiato** (No booking link available)

**Comment by leonlan** [comment]
Systems
- bookingsuedtirol.com
- ...

**Comment by leonlan** [comment]
avplanner

**Comment by leonlan** [comment]
- difficult experience booking huts https://www.facebook.com/groups/236463783972996/search/?q=list%20of%20huts

**Comment by leonlan** [comment]
https://www.facebook.com/photo.php?fbid=10160101099497833&set=p.10160101099497833&type=3 all huts by some FB person

**Comment by leonlan** [comment]
- http://www.altavia1dolomiti.com/rifugi  list of all AV1 huts
- https://www.rifuginrete.com/en/itinerari/tour-monte-bianco  mother websites

**Comment by leonlan** [comment]
[Gillian Price - Trekking in the Dolomites_ Alta Via 1 and Alta Via 2 with Alta Via 3--6 in outline-Cicerone Press (2016).epub.zip](https://github.com/user-attachments/files/16636045/Gillian.Price.-.Trekking.in.the.Dolomites_.Alta.Via.1.and.Alta.Via.2.with.Alta.Via.3--6.in.outline-Cicerone.Press.2016.epub.zip)

book but not read

**Comment by leonlan** [comment]
https://altaviadolomitibellunesi.it/en/complete-route/ super nice site

**Comment by leonlan** [comment]
not sure if worth it because 15/33 huts have no online booking system
